task-sync fix voor source branches

diff --git a/git-task-start b/git-task-start
--- a/git-task-start
+++ b/git-task-start
@@ -18,7 +18,7 @@ fi
 
 git checkout $srcBranch
 
-git task-sync $srcBranch || ( echo "git-task-sync failed"; exit 1 )
+git task-sync || ( echo "git-task-sync failed"; exit 1 )
 
 if [[ $task == task-* ]]; then
 	task=${task:5}
